version: '3.9'

services:
  backend:
    container_name: ${BACKEND_HOSTNAME}
    ports: 
      - "${BACKEND_PORT}:8080"
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    env_file:
      - .env
      - .env.local
  discord:
    container_name: ${DISCORD_BOT_NAME}
    build:
      context: ./packages/discord-bot
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.local
  database:
    container_name: ${DATABASE_NAME}
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"