version: '3.9'

services:
  backend:
    container_name: ${BACKEND_HOST}
    ports: 
      - ${BACKEND_PORT}:8080
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}

  discord:
    container_name: ${DISCORD_BOT_HOST}
    build:
      context: ./packages/discord-bot
      dockerfile: Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST: ${BACKEND_HOST}
      GUILD_ID: ${GUILD_ID}
    env_file:
      - .env.local

  # database:
  #   container_name: ${DATABASE_HOST}
  #   image: edgedb/edgedb
  #   environment:
  #     EDGEDB_SERVER_SECURITY: insecure_dev_mode
  #   volumes:
  #     - "./dbschema:/dbschema"
  #   ports:
  #     - ${DATABASE_PORT}:5656