[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.0-rc.4"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tonic = { version = "0.8", features = ["gzip"] }
http = "0.2"
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"
edgedb-tokio = { git = "https://github.com/edgedb/edgedb-rust", branch = "master" }
edgedb-derive = { git = "https://github.com/edgedb/edgedb-rust", branch = "master" }
edgedb-protocol = { git = "https://github.com/edgedb/edgedb-rust", branch = "master" }
uuid = { version = "1.2.1", features = ["v4", "serde"] }
prost = "0.11.0"
pbjson = "0.4"
pbjson-types = "0.4"
protoc-gen-prost = "0.2.0"
protoc-gen-prost-crate = {git = "https://github.com/neoeinstein/protoc-gen-prost", branch = "main"}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }