[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.16"
serde = "1.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
anyhow = "1.0"
edgedb-tokio = { git = "https://github.com/edgedb/edgedb-rust", branch = "master" }
edgedb-derive = { git = "https://github.com/edgedb/edgedb-rust", branch = "master" }
edgedb-protocol = { git = "https://github.com/edgedb/edgedb-rust", branch = "master" }
uuid = { version = "1.2.1", features = ["v4", "serde"] }
tonic = { version = "0.8", features = ["gzip"] }
prost = "0.11.0"
pbjson = "0.4"
pbjson-types = "0.4"